/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#424146",
        "tertiary-fixed-dim": "#c8c5cb",
        "surface-variant": "#34343c",
        "error": "#ffb4ab",
        "on-surface": "#e4e1eb",
        "secondary-fixed-dim": "#c6c6c6",
        "tertiary-fixed": "#e5e1e7",
        "surface-container-low": "#1b1b22",
        "on-surface-variant": "#d1c5b7",
        "secondary": "#c6c6c6",
        "primary-container": "#c8a97e",
        "surface-bright": "#393840",
        "error-container": "#93000a",
        "on-primary": "#402d0c",
        "inverse-on-surface": "#303037",
        "tertiary": "#cbc8ce",
        "surface-container-highest": "#34343c",
        "background": "#050508",
        "on-tertiary-fixed-variant": "#47464b",
        "on-primary-fixed": "#281800",
        "outline-variant": "#4e453b",
        "secondary-fixed": "#e2e2e2",
        "secondary-container": "#454747",
        "on-error": "#690005",
        "on-background": "#e4e1eb",
        "primary-fixed": "#ffddb0",
        "primary": "#e5c497",
        "surface-container": "#1f1f26",
        "tertiary-container": "#afadb3",
        "on-primary-container": "#533e1c",
        "on-tertiary": "#303034",
        "inverse-primary": "#735a36",
        "on-secondary-fixed-variant": "#454747",
        "primary-fixed-dim": "#e2c195",
        "surface": "#13131a",
        "surface-container-high": "#2a2931",
        "inverse-surface": "#e4e1eb",
        "on-secondary-fixed": "#1a1c1c",
        "on-secondary": "#2f3131",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#594320",
        "on-secondary-container": "#b4b5b5",
        "on-tertiary-fixed": "#1b1b1f",
        "surface-tint": "#e2c195",
        "outline": "#9a8f83",
        "surface-dim": "#13131a",
        "surface-container-lowest": "#0e0e14",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "160px",
        "margin-desktop": "80px",
        unit: "8px",
        "margin-mobile": "24px",
        "container-max": "1440px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "body-md": ["DM Sans"],
        "label-sm": ["DM Sans"],
        "display-lg": ["Playfair Display"],
        "headline-h2": ["Playfair Display"],
        "body-lg": ["DM Sans"],
        "headline-h3": ["Playfair Display"],
        "headline-h1": ["Playfair Display"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": [
          "12px",
          { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "500" },
        ],
        "display-lg": [
          "84px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "300" },
        ],
        "headline-h2": ["48px", { lineHeight: "1.3", fontWeight: "400" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "300" }],
        "headline-h3": ["32px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-h1": ["64px", { lineHeight: "1.2", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
};
